### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by byiringiroscar** [Yidnekachew-cmd/Leaderboard#4]
### code review

You have done a good job of Implementing the required requirements for the Leader project 🎆 

However, I would like to suggest you add some little changes 👍 

- Instead of checking Empty input on the lines below make it simple by adding the required on the input field 👍  just Use **KISS**
https://github.com/Yidnekachew-cmd/Leaderboard/blob/15be1c19ea1daa0302090949bdb8b9403706d610/src/modules/addScore.js#L5-L11
- I would like to suggest you improve the readme structure and remember to add a Hosted link for this project it seems like not working when you click the Deployment link 👍 
 
![image](https://user-images.githubusercontent.com/51321655/225548111-c16cbbf6-61cc-4181-8c7b-6e1a063b4ad0.png)

- Good job for implementing the function but I would like to suggest you use class and combine all in it [OPTIONAL] 😄 

happy coding 👏 👏 👏

**Comment by Yidnekachew-cmd** [comment]
Thank You!
